Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

==>Yes, there is a difference in the data type of the variables list_ and array_list.

The variable list_ is a standard Python list, and the elements in this list are of type 'str' (string), as the elements are enclosed in single quotes ('1', '2', '3', '4', '5').

On the other hand, the variable array_list is a Numpy array. When you create a Numpy array from a list of strings, it converts the elements to a common data type, based on the values present in the list


In [6]:
#To print the data types of both variables, you can use the following code:
import numpy as np
list_=['1','2','3','4','5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [15]:
import numpy as np
list_=['1','2','3','4','5']
array_list = np.array(object=list_)

print("Datatype of element in  list_:")
for ele in list_:
    print(type(ele))
    
print("Datatype of element in  array_list:")
for ele in array_list:
    print(ele.dtype)

Datatype of element in  list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Datatype of element in  array_list:
<U1
<U1
<U1
<U1
<U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

==>Yes, absouletly there will be changes occur all the elements present in arr_list variable become integar. 

Here the Code:-

In [18]:
import numpy as np
list_=['1','2','3','4','5']
array_list = np.array(object=list_, dtype = int)

print("Datatype of element in  list_:")
for ele in list_:
    print(type(ele))
    
print("Datatype of element in  array_list:")
for ele in array_list:
    print(ele.dtype)

Datatype of element in  list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Datatype of element in  array_list:
int32
int32
int32
int32
int32


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [20]:
np.shape(num_array)

(2, 3)

In [21]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
#Here the code to create to 3x3 matrix using array  function
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [29]:
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
